### ISSUE TITLE
Separation between contract and address explorers

### ISSUE THREAD

**Issue by htadashi** [apoorvlathey/eth-explorers-extension#17]
Some tools are exclusive to the analysis of contracts, for example, bytegraph, abi.w1nt3r.xyz and remix. It would make sense to separate them in a new extension (e.g. `eth-contract-explorers`)?

**Comment by apoorvlathey** [comment]
I am working on a new approach that's user-friendly. Instead of installing separate extensions and selecting the explorers from a dropdown, I am building a single UI to aggregate that:
https://twitter.com/apoorvlathey/status/1673218261910183939
![image](https://github.com/apoorvlathey/eth-explorers-extension/assets/20395316/7e59de37-9b29-4ff7-bcbf-660035a165d9)

**Comment by htadashi** [comment]
It is looking great! Looking forward to it! :)
